version: '2'
services:
  web:
    image: php:7.1
    volumes:
      - .:${PWD}
    command: php -S 0.0.0.0:8000 -t ${PWD}/web
    ports:
     - "8000:8000"
    environment:
      - DB_DSN=pgsql:dbname=postgres;host=db
      - DB_REDIS_HOST=redis

