<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/app.css">
    <script type="application/javascript" src="assets/app.js"></script>
</head>
<body>

<div class="content">
    <div class="row">
        <div class="col-xs-6 col-md-4"></div>
        <div class="col-xs-6 col-md-4">

            <form method="get">
                <div class="input-group date">
                    <input id="date" name="date" type="text" class="form-control">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                </div>
            </form>

            <?php/** @var $films \app\service\kinopoisk\FilmInterface[] */ ?>
            <?php if (!count($films)) { ?>
                <p class="bg-success">
                    Данных за эту дату ещё нет
                </p>
            <?php } else { ?>

                <table class="table">
                    <thead>
                    <tr>
                        <td>Позиция</td>
                        <td>Рейтинг</td>
                        <td>Название</td>
                        <td>Год</td>
                        <td>Голосов</td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($films as $film) { ?>
                        <tr>
                            <td><?= $film->getPosition() ?></td>
                            <td><?= $film->getRating() ?></td>
                            <td><?= $film->getName() ?></td>
                            <td><?= $film->getYear() ?></td>
                            <td><?= $film->getNumberVoted() ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            <?php } ?>
        </div>
        <div class="col-xs-6 col-md-4"></div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>
</html>